# Generated by Django 4.2.9 on 2024-02-10 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='org',
        ),
        migrations.RemoveField(
            model_name='user',
            name='position',
        ),
    ]
